server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 190713
    url: jdbc:mysql://localhost:3306/home?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
